# .pre-commit-config.yaml
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-xml
      - id: check-yaml
        args: [--allow-multiple-documents]
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace
      - id: check-docstring-first
      - id: check-added-large-files
      - id: check-json
      - id: check-toml

  # -------------------------
  # Python 格式化
  # -------------------------
  - repo: https://github.com/psf/black
    rev: 26.1.0
    hooks:
      - id: black
        language_version: python3.10

  - repo: https://github.com/pycqa/flake8
    rev: 7.3.0
    hooks:
      - id: flake8
        args: ["--max-line-length", "120"]


  # -------------------------
  # Rust 格式化
  # -------------------------
  - repo: local
    hooks:
      - id: cargo-fmt
        name: Rust cargo fmt
        entry: cargo fmt --all
        language: system
        types: [rust]
        pass_filenames: false
